CREATE TABLE IF NOT EXISTS Cliente(
    id SERIAL PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    cpf VARCHAR(11) NOT NULL
);

CREATE TABLE IF NOT EXISTS Usuario(
    id SERIAL PRIMARY KEY,
    nome_completo VARCHAR(120) NOT NULL,
    email VARCHAR(120) UNIQUE NOT NULL,
    senha_hash TEXT NOT NULL,
    senha_salt TEXT NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Lista(
    id SERIAL PRIMARY KEY,
    usuario_id INT NOT NULL REFERENCES Usuario(id) ON DELETE CASCADE,
    nome VARCHAR(120) NOT NULL,
    descricao TEXT NOT NULL,
    data_evento DATE,
    pix_eligivel BOOLEAN NOT NULL DEFAULT TRUE,
    criada_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ListaItem(
    id SERIAL PRIMARY KEY,
    lista_id INT NOT NULL REFERENCES Lista(id) ON DELETE CASCADE,
    nome VARCHAR(120) NOT NULL,
    imagem TEXT,
    preco DOUBLE PRECISION NOT NULL,
    arrecadado DOUBLE PRECISION NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Contribuicao(
    id SERIAL PRIMARY KEY,
    lista_item_id INT NOT NULL REFERENCES ListaItem(id) ON DELETE CASCADE,
    usuario_id INT REFERENCES Usuario(id) ON DELETE SET NULL,
    valor DOUBLE PRECISION NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);